# +-----------------------------------------------------
# |         SERVER AS400 CONFIG
# +-----------------------------------------------------
as400:
  hostname: localhost
  port: 42400

# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 9091
  servlet:
    context-path: /servicio1
    session:
      cookie:
        name: UISESSION