# +-----------------------------------------------------
# |         SERVER AS400 CONFIG
# +-----------------------------------------------------
as400:
  hostname: as400-service
  port: 42400

# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 52001
  servlet:
    context-path: /apisaldos
    session:
      cookie:
        name: UISESSION