# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 20-Abril-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de 2 contendores uno para la aplicacion
# -              y otro para la base de datos de la app de seguridad
# -------------------------------------------------------------------

version: '3.7'
services:
  db_proxysap:
    image: mysql
    container_name: db_proxysap
    hostname: db_proxysap
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'proxysapdb'
      MYSQL_USER: 'proxysap'
      MYSQL_PASSWORD: 'proxysap2020++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '6605:3306'
    volumes:
      - ./src/main/resources/databases/mysql-proxysap-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-proxysap-schema-v0.1.sql
      #- data_security:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/", "-h", "localhost"]
      timeout: 20s
      retries: 10
  proxysap-service:
    image: proxysap-service:latest
    container_name: proxysap-service
    hostname: proxysap-service
    restart: always
    ports:
      - 8050:8050
    networks:
      - backend
    depends_on:
      - db_proxysap
    environment:
      - SERVICE_PORTS=8050
      - DATABASE_HOST=db_proxysap
      - DATABASE_USER=proxysap
      - DATABASE_PASSWORD=proxysap2020++
      - DATABASE_NAME=proxysapdb
      - DATABASE_PORT=3306
volumes:
  data_security:
networks:
  backend:
    external: true