# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 20-Abril-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de 2 contendores uno para la aplicacion
# -              y otro para la base de datos de la app de seguridad
# -------------------------------------------------------------------

version: '3.7'
services:
  db_proveedores:
    image: mysql
    container_name: db_proveedores
    hostname: db_proveedores
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'proveedoresdb'
      MYSQL_USER: 'proveedores'
      MYSQL_PASSWORD: 'proveedores2020++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '6601:3306'
    volumes:
      - ./src/main/resources/databases/mysql-proveedores-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-proveedores-schema-v0.1.sql
      #- data_security:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"pinghttps://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/", "-h", "localhost"]
      timeout: 20s
      retries: 10
  proveedores-service:
    image: proveedores-service:latest
    container_name: proveedores-service
    hostname: proveedores-service
    restart: always
    ports:
      - 9091:9091
    networks:
      - backend
    depends_on:
      - db_proveedores
    environment:
      - SERVICE_PORTS=9091
      - DATABASE_HOST=db_proveedores
      - DATABASE_USER=proveedores
      - DATABASE_PASSWORD=proveedores2020++
      - DATABASE_NAME=proveedoresdb
      - DATABASE_PORT=6601
volumes:
  data_security:
networks:
  backend:
    driver: bridge