-- MySQL Script generated by MySQL Workbench
-- Mon May 01 16:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proveedoresdb
-- -----------------------------------------------------
-- Base de datos que permite controlar el consumo de los servicios a traves del proxy
DROP SCHEMA IF EXISTS `proxysapdb` ;

-- -----------------------------------------------------
-- Schema proveedoresdb
--
-- Base de datos que permite controlar el manejo de los proveedores para el banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proxysapdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `proxysapdb` ;

-- -----------------------------------------------------
-- Table `proxysapdb`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proxysapdb`.`auditoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proxysapdb`.`auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `servicio`      VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_auditoria`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PROVEEDOR_UNIQUE` ON `proxysapdb`.`auditoria` (`id_auditoria` ASC);

SHOW WARNINGS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `proxysapdb`.`auditoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `proxysapdb`;
INSERT INTO `proxysapdb`.`auditoria` (`id_auditoria`, `servicio`, `descripcion`) VALUES (1, 'PROVEEDORES', 'Proveedor: Gas');

COMMIT;