# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 01-Abril-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de una imagen docker con un api rest que
# -              valida el usuario registrado en un sistema sap
# -------------------------------------------------------------------

version: '3.7'
services:
  sap-service:
    image: sap-service:latest
    container_name: sap-service
    hostname: sap-service
    restart: always
    ports:
      - 55725:55725
    networks:
      - backend
networks:
  backend:
    external: true