-- MySQL Script generated by MySQL Workbench
-- Mon May 01 16:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema routingdb
-- -----------------------------------------------------
-- Base de datos que permite controlar la seguridad para mis servicios rest
DROP SCHEMA IF EXISTS `routingdb` ;

-- -----------------------------------------------------
-- Schema routingdb
--
-- Base de datos que permite controlar la seguridad para mis servicios rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `routingdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `routingdb` ;

-- -----------------------------------------------------
-- Table `routingdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `routingdb`.`routing` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `routingdb`.`routing` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `END_POINT` VARCHAR(100) NOT NULL,
  `NOMBRE_SERVICIO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ROUTING_UNIQUE` ON `routingdb`.`routing` (`ID` ASC);

SHOW WARNINGS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `routingdb`.`routing`
-- -----------------------------------------------------
START TRANSACTION;
USE `routingdb`;
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:52001/apisaldos/api/v1.0/saldos/', 'SALDOS');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:55725/sap/SapService?wsdl', 'SAP');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:9090/api/domiciliacion/factura', 'FACTURAS');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:9091/servicios/pagos/v1/payments/', 'AGUA');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:8080/gas-service/PagosService?wsdl', 'GAS');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:7070/apiconvenios/api/v1.0/convenios', 'CONVENIOS');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:8040/apimail/api/v1.0/email/', 'EMAIL');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:8050/apiproxy/api/v1.0/proveedores', 'PROXYPROVEEDORES');
INSERT INTO `routingdb`.`routing` (`END_POINT`,`NOMBRE_SERVICIO`) VALUES ('http://localhost:8060/apiproveedores/api/v1.0/proveedores', 'PROVEEDORES');

COMMIT;