-- MySQL Script generated by MySQL Workbench
-- Mon May 01 16:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema routingdb
-- -----------------------------------------------------
-- Base de datos que permite controlar la seguridad para mis servicios rest
DROP SCHEMA IF EXISTS `routingdb` ;

-- -----------------------------------------------------
-- Schema routingdb
--
-- Base de datos que permite controlar la seguridad para mis servicios rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `routingdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `routingdb` ;

-- -----------------------------------------------------
-- Table `routingdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `routingdb`.`routing` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `routingdb`.`routing` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `END_POINT` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ROUTING_UNIQUE` ON `routingdb`.`routing` (`ID` ASC);

SHOW WARNINGS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `routingdb`.`routing`
-- -----------------------------------------------------
START TRANSACTION;
USE `routingdb`;
INSERT INTO `routingdb`.`routing` (`END_POINT`) VALUES ('http://EndPoint1');
INSERT INTO `routingdb`.`routing` (`END_POINT`) VALUES ('http://EndPoint2');
INSERT INTO `routingdb`.`routing` (`END_POINT`) VALUES ('http://EndPoint3');

COMMIT;