-- MySQL Script generated by MySQL Workbench
-- Mon May 01 16:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proveedoresdb
-- -----------------------------------------------------
-- Base de datos que permite controlar el manejo de los proveedores para el banco
DROP SCHEMA IF EXISTS `proveedoresdb` ;

-- -----------------------------------------------------
-- Schema proveedoresdb
--
-- Base de datos que permite controlar el manejo de los proveedores para el banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proveedoresdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `proveedoresdb` ;

-- -----------------------------------------------------
-- Table `proveedoresdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedoresdb`.`proveedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedoresdb`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre`      VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha`       DATETIME NOT NULL,
  `activo`      BOOLEAN NOT NULL,
  `compensacion` BOOLEAN NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PROVEEDOR_UNIQUE` ON `proveedoresdb`.`proveedor` (`id_proveedor` ASC);

SHOW WARNINGS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `proveedoresdb`.`proveedor`
-- -----------------------------------------------------
START TRANSACTION;
USE `proveedoresdb`;
INSERT INTO `proveedoresdb`.`proveedor` (`id_proveedor`, `nombre`, `descripcion`, `fecha`, `activo`, `compensacion`) VALUES (1, 'PROVEEDOR_PRUEBA', 'pruebas', NOW(), TRUE, TRUE);

COMMIT;