-- MySQL Script generated by MySQL Workbench
-- Mon May 01 16:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conveniosdb
-- -----------------------------------------------------
-- Base de datos que permite controlar la seguridad para mis servicios rest
DROP SCHEMA IF EXISTS `conveniosdb` ;

-- -----------------------------------------------------
-- Schema conveniosdb
--
-- Base de datos que permite controlar la seguridad para mis servicios rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conveniosdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `conveniosdb` ;

-- -----------------------------------------------------
-- Table `conveniosdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conveniosdb`.`convenio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conveniosdb`.`convenio` (
  `id_convenio` INT NOT NULL AUTO_INCREMENT,
  `nombre`      VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha`       DATETIME NOT NULL,
  `activo`      BOOLEAN NOT NULL,
  `proveedor`   INT NOT NULL,
  PRIMARY KEY (`id_convenio`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CONVENIO_UNIQUE` ON `conveniosdb`.`convenio` (`id_convenio` ASC);

SHOW WARNINGS;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `conveniosdb`.`convenio`
-- -----------------------------------------------------
START TRANSACTION;
USE `conveniosdb`;
INSERT INTO `conveniosdb`.`convenio` (`id_convenio`, `nombre`, `descripcion`, `fecha`, `activo`, `proveedor`) VALUES (1, 'CONVENIO_PRUEBA', 'pruebas', NOW(), TRUE, 1);

COMMIT;